stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    - data/external/water_potability.csv
    params:
    - data_collection.test_size
    - data_collection.random_state
    outs:
    - data/raw

  pre_processing:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw
    - src/data/data_prep.py
    outs:
    - data/processed

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed
    - src/models/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl
    
  model_eval:
    cmd: python src/models/model_eval.py
    deps:
      - src/models/model_eval.py
      - models/model.pkl
      - data/processed/test_processed.csv   # only if your eval uses this
    metrics:
      - reports/metrics.json

